spring:
  application:
    name: spring-security-deep-dive
  security:
    user:
      name: mwas
      password: mwas12345
  datasource:
    url: jdbc:postgresql://localhost:5430/Bills-management
    username: postgres
    password: mwas
    driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
